radiusdisk = 1.0                      #All disks have the same: radius,
massdisk = 1.0                        #mass
velocitydisk = 1.0                    #and velocity norm.
Lx1 = 0                                #Coordinates origin(x and
Ly1 = 0                                #y)
maxholesize = 0.5*radiusdisk          #Maximum hole size of the vertical shared wall
cellforinitialparticle = 1             #The cell where the particle departs
radiusparticle = 0.02                  #Just for visualization
massparticle = 1.0
numberofcells = 5
size_x = 3.
size_y = 3.
velocityparticle = 1.0
t_i = 0
t_max = 100
